### ISSUE TITLE
Bug marketwatch.com no longer working (dev: livecoverage)

### ISSUE THREAD

**Issue by allgameplaya** [bpc-clone/bpc_chrome_support#628]
Always first see changelog and search (domain) name in (all) issues/options (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Marketwatch no longer works

Link of paywalled article: https://www.marketwatch.com/livecoverage/tesla-earnings-stock-q2-musk-results-guidance

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): Chrome

BPC-extension version (number): 4.1.6.5

**Comment by bpc-clone** [comment]
Site fixed in latest master (or next release).\
PS mandatory doesn't mean you can skip it ... >  `Actions you tried yourself (mandatory) and if it works`

**Comment by allgameplaya** [comment]
> PS mandatory doesn't mean you can skip it ... > `Actions you tried yourself (mandatory) and if it works`

Noted! ~~However, the issue is not fixed. Marketwatch seems to work but the /livecoverage/ URLs are still paywalled. Example: https://www.marketwatch.com/livecoverage/tesla-earnings-stock-q2-musk-results-guidance~~


~~Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Cleared cookies, disabled JS (Marketwatch displays "You are blocked!), changed user-agent, reader view, archive sites and add a custom site.~~

EDIT: Nevermind! I did not apply the update correctly. It works flawlessly in 4.1.6.6! Many thanks! 🙏🏽
